upgrade oragono to 2.4.0
hashbang/gitops pull request #62
Opened 2020-11-08 03:25 UTC by slingamn

`suppress-ident` was never included in a stable release and was replaced by `coerce-ident`.

2020-11-08 04:34 UTC, daurnimator requested changes

2020-11-08 04:34 UTC, daurnimator commented on ircd/kustomization.yaml
> -  - name: oragono/oragono:latest
You don't change this line unless you also change the deployment.

Just the digest change is sufficient.

2020-11-08 05:02 UTC, daurnimator approved these changes
Could you fixup your previous commit rather than reverting in a following commit?

Also see commit message convention for this repository.

2020-11-09 17:16 UTC, slingamn commented
Now that I think about it --- are we sure this will work? It looks like that hash is only available under the `v2.4.0` tag:

https://hub.docker.com/layers/oragono/oragono/v2.4.0/images/sha256-fd82b67b10cb8e9458d3036f4aab9ca0182b4dacba17f3164a45d1f4fe3a5263

and not under the `latest` tag:

https://hub.docker.com/layers/oragono/oragono/latest/images/sha256-fd82b67b10cb8e9458d3036f4aab9ca0182b4dacba17f3164a45d1f4fe3a5263

2020-11-09 18:27 UTC, merged